// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -InFile mainwindow.ui -OutFile mainwindow_ui.go

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type MainWindowUi struct {
	MainWindow    *qt.QMainWindow
	centralwidget *qt.QWidget
	menubar       *qt.QMenuBar
	statusbar     *qt.QStatusBar
}

// NewMainWindowUi creates all Qt widget classes for MainWindow.
func NewMainWindowUi() *MainWindowUi {
	ui := &MainWindowUi{}

	ui.MainWindow = qt.NewQMainWindow(nil)
	ui.MainWindow.Resize(1280, 720)
	ui.MainWindow.SetWindowTitle("gcharted")

	ui.centralwidget = qt.NewQWidget(ui.MainWindow.QWidget)
	ui.MainWindow.SetCentralWidget(ui.centralwidget) // Set central widget

	ui.menubar = qt.NewQMenuBar(ui.MainWindow.QWidget)
	ui.menubar.Resize(1280, 22)
	ui.MainWindow.SetMenuBar(ui.menubar)

	ui.statusbar = qt.NewQStatusBar(ui.MainWindow.QWidget)
	ui.MainWindow.SetStatusBar(ui.statusbar)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *MainWindowUi) Retranslate() {

}
