// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate go run ../../scripts/uic/uic.go "-InFile" "mainwindow.ui" "-OutFile" "mainwindow_ui.go" "-Package" "gui"

package gui

import (
	"github.com/MatusOllah/gcharted/i18n"
	qt "github.com/mappu/miqt/qt6"
)

type MainWindowUi struct {
	MainWindow                *qt.QMainWindow
	centralwidget             *qt.QWidget
	graphicsView              *qt.QGraphicsView
	menubar                   *qt.QMenuBar
	menuFile                  *qt.QMenu
	menuHelp                  *qt.QMenu
	toolbar                   *qt.QToolBar
	statusbar                 *qt.QStatusBar
	vuMeterDockWidget         *qt.QDockWidget
	vuMeterDockWidgetContents *qt.QWidget
	noteDockWidget            *qt.QDockWidget
	noteDockWidgetContents    *qt.QWidget
	sectionDockWidget         *qt.QDockWidget
	sectionDockWidgetContents *qt.QWidget
	songDockWidget            *qt.QDockWidget
	songDockWidgetContents    *qt.QWidget
	actionAbout               *qt.QAction
	actionAbout_Qt            *qt.QAction
	actionExit                *qt.QAction
}

// NewMainWindowUi creates all Qt widget classes for MainWindow.
func NewMainWindowUi() *MainWindowUi {
	ui := &MainWindowUi{}

	ui.MainWindow = qt.NewQMainWindow(nil)
	ui.MainWindow.SetObjectName(*qt.NewQAnyStringView3("MainWindow"))
	ui.MainWindow.Resize(1280, 720)
	ui.MainWindow.SetWindowTitle("GCharted")
	icon0 := qt.NewQIcon()
	icon0.AddFile4(":/icons/gcharted.png", qt.NewQSize(), qt.QIcon__Normal, qt.QIcon__Off)
	ui.MainWindow.SetWindowIcon(icon0)

	ui.actionAbout = qt.NewQAction()
	ui.actionAbout.SetObjectName(*qt.NewQAnyStringView3("actionAbout"))

	ui.actionAbout_Qt = qt.NewQAction()
	ui.actionAbout_Qt.SetObjectName(*qt.NewQAnyStringView3("actionAbout_Qt"))

	ui.actionExit = qt.NewQAction()
	ui.actionExit.SetObjectName(*qt.NewQAnyStringView3("actionExit"))

	ui.centralwidget = qt.NewQWidget(ui.MainWindow.QWidget)
	ui.centralwidget.SetObjectName(*qt.NewQAnyStringView3("centralwidget"))

	ui.graphicsView = qt.NewQGraphicsView(ui.centralwidget)
	ui.graphicsView.SetObjectName(*qt.NewQAnyStringView3("graphicsView"))
	ui.graphicsView.Resize(860, 654)
	ui.MainWindow.SetCentralWidget(ui.centralwidget) // Set central widget

	ui.menubar = qt.NewQMenuBar(ui.MainWindow.QWidget)
	ui.menubar.SetObjectName(*qt.NewQAnyStringView3("menubar"))
	ui.menubar.Resize(1280, 33)

	ui.menuFile = qt.NewQMenu(ui.menubar.QWidget)
	ui.menuFile.SetObjectName(*qt.NewQAnyStringView3("menuFile"))
	ui.menuFile.QWidget.AddAction(ui.actionExit)

	ui.menuHelp = qt.NewQMenu(ui.menubar.QWidget)
	ui.menuHelp.SetObjectName(*qt.NewQAnyStringView3("menuHelp"))
	ui.menuHelp.QWidget.AddAction(ui.actionAbout)
	ui.menuHelp.QWidget.AddAction(ui.actionAbout_Qt)
	ui.menubar.AddMenu(ui.menuFile)
	ui.menubar.AddMenu(ui.menuHelp)
	ui.MainWindow.SetMenuBar(ui.menubar)

	ui.toolbar = qt.NewQToolBar(ui.MainWindow.QWidget)
	ui.toolbar.SetObjectName(*qt.NewQAnyStringView3("toolbar"))
	ui.MainWindow.AddToolBar(qt.TopToolBarArea, ui.toolbar)
	/* miqt-uic: no handler for toolbar attribute 'toolBarBreak' */

	ui.statusbar = qt.NewQStatusBar(ui.MainWindow.QWidget)
	ui.statusbar.SetObjectName(*qt.NewQAnyStringView3("statusbar"))
	ui.MainWindow.SetStatusBar(ui.statusbar)

	ui.vuMeterDockWidget = qt.NewQDockWidget(ui.MainWindow.QWidget)
	ui.vuMeterDockWidget.SetObjectName(*qt.NewQAnyStringView3("vuMeterDockWidget"))
	ui.MainWindow.AddDockWidget(qt.DockWidgetArea(1), ui.vuMeterDockWidget)

	ui.vuMeterDockWidgetContents = qt.NewQWidget(ui.vuMeterDockWidget.QWidget)
	ui.vuMeterDockWidgetContents.SetObjectName(*qt.NewQAnyStringView3("vuMeterDockWidgetContents"))
	ui.vuMeterDockWidget.SetWidget(ui.vuMeterDockWidgetContents) // Set central widget

	ui.noteDockWidget = qt.NewQDockWidget(ui.MainWindow.QWidget)
	ui.noteDockWidget.SetObjectName(*qt.NewQAnyStringView3("noteDockWidget"))
	ui.MainWindow.AddDockWidget(qt.DockWidgetArea(2), ui.noteDockWidget)

	ui.noteDockWidgetContents = qt.NewQWidget(ui.noteDockWidget.QWidget)
	ui.noteDockWidgetContents.SetObjectName(*qt.NewQAnyStringView3("noteDockWidgetContents"))
	ui.noteDockWidget.SetWidget(ui.noteDockWidgetContents) // Set central widget

	ui.sectionDockWidget = qt.NewQDockWidget(ui.MainWindow.QWidget)
	ui.sectionDockWidget.SetObjectName(*qt.NewQAnyStringView3("sectionDockWidget"))
	ui.MainWindow.AddDockWidget(qt.DockWidgetArea(2), ui.sectionDockWidget)

	ui.sectionDockWidgetContents = qt.NewQWidget(ui.sectionDockWidget.QWidget)
	ui.sectionDockWidgetContents.SetObjectName(*qt.NewQAnyStringView3("sectionDockWidgetContents"))
	ui.sectionDockWidget.SetWidget(ui.sectionDockWidgetContents) // Set central widget

	ui.songDockWidget = qt.NewQDockWidget(ui.MainWindow.QWidget)
	ui.songDockWidget.SetObjectName(*qt.NewQAnyStringView3("songDockWidget"))
	ui.MainWindow.AddDockWidget(qt.DockWidgetArea(2), ui.songDockWidget)

	ui.songDockWidgetContents = qt.NewQWidget(ui.songDockWidget.QWidget)
	ui.songDockWidgetContents.SetObjectName(*qt.NewQAnyStringView3("songDockWidgetContents"))
	ui.songDockWidget.SetWidget(ui.songDockWidgetContents) // Set central widget

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *MainWindowUi) Retranslate() {
	ui.actionAbout.SetText(i18n.L("About"))
	ui.actionAbout_Qt.SetText(i18n.L("AboutQt"))
	ui.actionExit.SetText(i18n.L("Exit"))
	ui.menuFile.SetTitle(i18n.L("File"))
	ui.menuHelp.SetTitle(i18n.L("Help"))
	ui.toolbar.SetWindowTitle(i18n.L("Toolbar"))
	ui.vuMeterDockWidget.SetWindowTitle(i18n.L("VUMeter"))
	ui.noteDockWidget.SetWindowTitle(i18n.L("Note"))
	ui.sectionDockWidget.SetWindowTitle(i18n.L("Section"))
	ui.songDockWidget.SetWindowTitle(i18n.L("Song"))
}
