// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate scripts/uic/uic.go "-InFile" "internal/gui/mainwindow.ui" "-OutFile" "internal/gui/mainwindow_ui.go" "-Package" "gui"

package gui

import (
	qt "github.com/mappu/miqt/qt6"
)

type MainWindowUi struct {
	MainWindow    *qt.QMainWindow
	centralwidget *qt.QWidget
	menubar       *qt.QMenuBar
	statusbar     *qt.QStatusBar
}

// NewMainWindowUi creates all Qt widget classes for MainWindow.
func NewMainWindowUi() *MainWindowUi {
	ui := &MainWindowUi{}

	ui.MainWindow = qt.NewQMainWindow(nil)
	ui.MainWindow.SetObjectName(*qt.NewQAnyStringView3("MainWindow"))
	ui.MainWindow.Resize(1280, 720)
	ui.MainWindow.SetWindowTitle("gcharted")

	ui.centralwidget = qt.NewQWidget(ui.MainWindow.QWidget)
	ui.centralwidget.SetObjectName(*qt.NewQAnyStringView3("centralwidget"))
	ui.MainWindow.SetCentralWidget(ui.centralwidget) // Set central widget

	ui.menubar = qt.NewQMenuBar(ui.MainWindow.QWidget)
	ui.menubar.SetObjectName(*qt.NewQAnyStringView3("menubar"))
	ui.menubar.Resize(1280, 22)
	ui.MainWindow.SetMenuBar(ui.menubar)

	ui.statusbar = qt.NewQStatusBar(ui.MainWindow.QWidget)
	ui.statusbar.SetObjectName(*qt.NewQAnyStringView3("statusbar"))
	ui.MainWindow.SetStatusBar(ui.statusbar)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *MainWindowUi) Retranslate() {

}

